Added GitHib Actions.

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -11,12 +11,19 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Manual Docker Login (Temporary)
-        run: |
-          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_TOKEN }}
 
       - name: Test
         run: docker-compose run --rm app sh -c "python manage.py test"
+        id: test
+
+      - name: Check Test Result
+        if: steps.test.outcome == 'failure'
+        run: echo "Test failed, stopping workflow" && exit 1
 
       - name: Lint
         run: docker-compose run --rm app sh -c "flake8"
